resolver: lts-8.16

packages:
- './servant-zeppelin'
- './servant-zeppelin-server'
- './servant-zeppelin-swagger'
- './servant-zeppelin-client'


extra-deps:
 - servant-0.11
 - servant-server-0.11
 - servant-client-0.11
 - servant-swagger-1.1.3
 - haddock-api-2.17.4
